<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <RootNamespace>TerraRuntime.Network</RootNamespace>
    <AssemblyName>TerraRuntime.Network</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../TerraRuntime.Protocol/TerraRuntime.Protocol.csproj" />
  </ItemGroup>
</Project>
