namespace TerraRuntime.Operations;

internal readonly record struct RuntimeNetworkSnapshot(
    int ActiveConnections,
    int RegisteredConnections,
    long AcceptedConnections,
    long RejectedConnections,
    int TrackedOutboundQueues,
    long QueuedOutboundFrames,
    long QueuedOutboundBytes,
    long RejectedOutboundFrames,
    int SlowClients,
    ReadOnlyMemory<RuntimeConnectionQueueDetail> TopOutboundQueues,
    int TrackedInboundRates,
    long InboundWindowFrames,
    long InboundWindowBytes,
    long InboundTotalFrames,
    long InboundTotalBytes,
    long RejectedInboundFrames,
    ReadOnlyMemory<RuntimeConnectionRateDetail> TopInboundRates,
    long RelayedAppearanceFrames,
    long AppearanceBaselineFrames,
    long RelayedEquipmentFrames,
    long EquipmentBaselineFrames,
    long DroppedEquipmentSnapshotUpdates,
    long PlayerActiveBaselineFrames,
    long PlayerDeactivationFrames,
    long RelayedMovementFrames,
    long MovementResyncFrames,
    DateTimeOffset CapturedAtUtc,
    long NpcRelayedFrames = 0,
    long NpcBaselineFrames = 0,
    long NpcRejectedFrames = 0,
    long NpcUnsupportedCommits = 0,
    long ProjectileRelayedFrames = 0,
    long ProjectileBaselineFrames = 0,
    long ProjectileRejectedFrames = 0,
    long ProjectileUnsupportedCommits = 0);
