namespace TerraRuntime.Operations;

internal readonly record struct RuntimeWorldSnapshot(
    bool Ready,
    string Name,
    int WorldId,
    Guid UniqueId,
    int FormatVersion,
    ulong WorldGeneratorVersion,
    int WidthTiles,
    int HeightTiles,
    int TileCount,
    int ChestCount,
    int SignCount,
    int TownNpcCount,
    int PersistentNpcCount,
    int TileEntityCount,
    int PressurePlateCount,
    int TownRoomCount,
    bool RuntimeCacheHit,
    string InitialCacheResult,
    int CacheParallelReads,
    double FileReadMilliseconds,
    double CacheLoadMilliseconds,
    double CanonicalWorldLoadMilliseconds,
    double CacheWriteMilliseconds,
    double BootstrapMilliseconds,
    double WorldReadyMilliseconds,
    double NetworkReadyMilliseconds,
    DateTimeOffset CapturedAtUtc,
    bool RuntimeClockAvailable = false,
    double RuntimeTime = 0d,
    bool RuntimeDayTime = false,
    byte RuntimeMoonPhase = 0,
    double RuntimeSlimeRainTime = 0d,
    int RuntimeDayRate = 0,
    bool SectionCacheAvailable = false,
    int SectionCacheDirtyBacklog = 0,
    int SectionCacheInFlight = 0,
    int SectionCacheEntries = 0,
    int SectionCacheMaximumEntries = 0,
    long SectionCacheBytes = 0,
    long SectionCacheSubmitted = 0,
    long SectionCacheRejected = 0,
    long SectionCachePublished = 0,
    long SectionCacheStaleResults = 0,
    long SectionCacheEncodeFailures = 0,
    long SectionCachePublishRejections = 0,
    int SectionCacheActiveWorkers = 0,
    int SectionCachePendingWork = 0,
    double SectionCacheTotalEncodeMilliseconds = 0d);
