namespace TerraRuntime.Protocol;

/// <summary>
/// Verified message identifiers consumed by TerraRuntime's protocol boundaries.
/// Extend this catalog only from confirmed Terraria 1.4.5.8 / protocol-326 evidence.
/// </summary>
public enum TerrariaMessageId : byte
{
    Hello = 1,
    Kick = 2,
    PlayerInfo = 3,
    SyncPlayer = 4,
    SyncEquipment = 5,
    RequestWorldData = 6,
    WorldData = 7,
    SpawnTileData = 8,
    StatusTextSize = 9,
    TileSection = 10,
    TileFrameSection = 11,
    PlayerSpawn = 12,
    PlayerControls = 13,
    PlayerActive = 14,
    PlayerHp = 16,
    TileManipulation = 17,
    DoorToggle = 19,
    TileSquare = 20,
    WorldItemDrop = 21,
    WorldItemOwner = 22,
    NpcUpdate = 23,
    ChatMessage = 25,
    ProjectileNew = 27,
    NpcDamage = 28,
    ProjectileDestroy = 29,
    RequestChestOpen = 31,
    SyncChestItem = 32,
    SyncPlayerChest = 33,
    PlayerMana = 42,
    RequestSign = 46,
    SignNew = 47,
    LiquidSet = 48,
    PlayerSpawnSelf = 49,
    SetNpcTalk = 40,
    UniqueTownNpcInfoSyncRequest = 56,
    UpdateNpcHome = 60,
    ChestName = 69,
    CatchNpc = 70,
    TravelShop = 72,
    PlaceObject = 79,
    SyncPlayerChestIndex = 80,
    LoadNetModule = 82,
    FinishedConnectingToServer = 129,
    InstancedItemSlotRelease = 151,
    SyncChestSize = 155,
    NpcDamageAck = 162
}
