using TerraRuntime.World;
using TerraRuntime.WorldGeneration.Vanilla;

namespace TerraRuntime.Tests;

public sealed class DungeonObjectFraming1458Tests
{
    [Theory]
    [InlineData(21, 0)]
    [InlineData(21, 2)]
    [InlineData(21, 27)]
    [InlineData(467, 13)]
    public void Supported_chest_and_adjacent_dart_trap_survive_decoration_framing(int type, int style)
    {
        WorldTileStore tiles = Fixture((ushort)type, style);
        WorldTile[] before = tiles.Tiles.ToArray();
        var random = new DungeonSurfaceBuildings1458Tests.RandomAdapter(1458);
        new DungeonObjectPlacement1458(tiles, random).FrameSquare(30, 30);
        Assert.Equal(before, tiles.Tiles.ToArray());
        Assert.Equal(new DungeonSurfaceBuildings1458Tests.RandomAdapter(1458).Next(), random.Next());
    }

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public void Damaged_chest_does_not_bypass_its_side_table(bool missingSupport)
    {
        WorldTileStore tiles = Fixture(21, 2);
        tiles.Set(29, missingSupport ? 32 : 30, default);
        var random = new DungeonSurfaceBuildings1458Tests.RandomAdapter(1458);
        Assert.Throws<InvalidOperationException>(() => new DungeonObjectPlacement1458(tiles, random).FrameSquare(30, 30));
    }

    // Also consumed as input by the ignored original-server oracle; output is not generated by runtime code.
    internal static WorldTileStore Fixture(ushort type, int style)
    {
        var tiles = new WorldTileStore(new WorldDimensions(80, 80));
        for (int x = 29; x <= 30; x++)
        {
            for (int y = 30; y <= 31; y++)
                tiles.Set(x, y, new WorldTile { Type = type, Flags = WorldTileFlags.Active | WorldTileFlags.WireRed,
                    FrameX = (short)(style * 36 + (x - 29) * 18), FrameY = (short)((y - 30) * 18), Wall = 7, TileColor = 3 });
            // CheckChest checks active + tileSolid, not nactive/SolidTile; shape and actuator are deliberate.
            tiles.Set(x, 32, new WorldTile { Type = 41, Flags = WorldTileFlags.Active | WorldTileFlags.Inactive, Shape = 2 });
        }
        tiles.Set(31, 29, new WorldTile { Type = 137, Flags = WorldTileFlags.Active | WorldTileFlags.WireRed,
            FrameX = 18, FrameY = 0, Wall = 7, TileColor = 4 });
        return tiles;
    }
}
