using System.Runtime.InteropServices;
using System.Security.Cryptography;
using TerraRuntime.Contracts.Gameplay;
using TerraRuntime.World;

namespace TerraRuntime.Tests;

public sealed class UnderworldTerrain1458Tests
{
    // Independently compared tile-by-tile and next-RNG against the pinned official Linux 1.4.5.8
    // WorldGen.TileRunner, not generated by an expected-value copy of our implementation.
    [Theory]
    [InlineData(57,200,19,1000,true,0,2,true,1879225131,"A9280094B820D86F17BCEC2FAE885ED22C3CB498BF03156E9386EDDB51A2FFCD")]
    [InlineData(57,250,29,23,true,-1,.3,false,1031356133,"96609FE6AD3D07CFAF689A12123F03F876AE71788F5745829F2950C60BB78802")]
    [InlineData(58,265,6,6,false,0,0,false,1666684478,"D4A61DDAFEA70A0269367C3F7A0E41B5E9EEB1609096D3E7B2B19AE90F8D2B80")]
    [InlineData(-2,260,25,19,false,2,-1,false,205458176,"6BD5CFBFE3D16397C31BFE0B7B8D2516C01DAADAD36A80DC04E9DB4A81FF54A7")]
    [InlineData(-2,70,12,9,false,0,0,false,1025871111,"F82517D737DD9B23E2DE708ED03971446876EC18FB3961B97A4B3A879D82E61C")]
    [InlineData(-2,140,12,9,false,0,0,false,611808157,"7041FBD739347011C19B7600779E82E8229FC10CCA556A65E82F2C115CC27171")]
    [InlineData(57,40,20,15,true,0,1,true,905421089,"C401A6991878DBA2E81009442DD32187C4F328A4F748D6BBDC948F945243F5A5")]
    public void Small_runners_match_official_tile_and_rng_golden(int type, int cy, double strength, int steps,
        bool add, double sx, double sy, bool noY, int next, string expectedHash)
    {
        const int width = 96, height = 320;
        var store = new WorldTileStore(new WorldDimensions(width, height));
        ushort[] types = [0,1,3,21,45,53,57,58,147,189,190,196,396,397,400,401,404,368,367,41,43,44,481,482,483,226,237,460,717,718,719];
        for (int x = 0; x < width; x++)
        for (int y = 0; y < height; y++)
            store.Tiles[store.GetUncheckedIndex(x, y)] = new WorldTile
            {
                Type = types[(x * 13 + y * 7) % types.Length], Wall = 13,
                Flags = (x + y) % 5 != 0 ? WorldTileFlags.Active : 0,
                LiquidAmount = (byte)((x + y) % 7 == 0 ? 127 : 0), LiquidKind = (WorldLiquidKind)((x + y) % 4)
            };
        var random = new SeededRandom(42);
        new SmallTerrainRunner1458(store, random, 50, new(80, 200), TestContext.Current.CancellationToken)
            .Run(48, cy, strength, steps, type, add, sx, sy, noY);
        Assert.Equal(next, random.Next());
        var normalized = new WorldTile[width * height];
        for (int x = 0; x < width; x++)
        for (int y = 0; y < height; y++) normalized[x * height + y] = store.Get(x, y);
        Assert.Equal(expectedHash, Convert.ToHexString(SHA256.HashData(MemoryMarshal.AsBytes(normalized.AsSpan()))));
    }

    [Fact]
    public void Roof_and_basin_preserve_metadata_and_do_not_create_a_solid_floor()
    {
        const int height = 400;
        var store = new WorldTileStore(new WorldDimensions(50, height));
        var original = new WorldTile { Type = 161, Wall = 71, FrameX = 18, FrameY = 36, Shape = 3,
            Flags = WorldTileFlags.Active | WorldTileFlags.WireRed, LiquidAmount = 23, LiquidKind = WorldLiquidKind.Shimmer };
        store.Tiles.Fill(original);
        UnderworldTerrain1458.CarveAndFill(store, new BasinRandom(), TestContext.Current.CancellationToken);
        Assert.Equal(original, store.Get(0, height - 191));
        WorldTile coat = original; coat.Type = 57;
        Assert.Equal(coat, store.Get(0, height - 190));
        WorldTile empty = original; empty.Flags &= ~WorldTileFlags.Active;
        empty.LiquidAmount = 0; empty.LiquidKind = WorldLiquidKind.Honey;
        Assert.Equal(empty, store.Get(0, height - 170));
        Assert.Equal(empty, store.Get(20, height - 1));
        Assert.Equal(empty, store.Get(9, height - 20));
        Assert.Equal(0, store.Get(10, height - 66).LiquidAmount);
        Assert.Equal(255, store.Get(10, height - 65).LiquidAmount);
        Assert.Equal(255, store.Get(14, height - 120).LiquidAmount); // -105 jumps to -120.
        Assert.Equal(0, store.Get(14, height - 121).LiquidAmount);
    }

    [Theory]
    [InlineData(-1,5,10)] [InlineData(59,5,10)] [InlineData(57,30,10)] [InlineData(57,5,1001)]
    public void Unadmitted_runner_modes_fail_before_mutation(int type, double strength, int steps)
    {
        var store = new WorldTileStore(new WorldDimensions(50, 400));
        var random = new SeededRandom(42);
        Assert.Throws<ArgumentOutOfRangeException>(() => new SmallTerrainRunner1458(store, random, 50, new(80, 200), TestContext.Current.CancellationToken)
            .Run(25, 200, strength, steps, type));
        Assert.Equal(new SeededRandom(42).Next(), random.Next());
        foreach (WorldTile tile in store.Tiles) Assert.Equal(default, tile);
    }

    private sealed class BasinRandom : IWorldGenerationVanillaRandom
    {
        public int Next(int min, int max) => (min, max) switch { (150,190) => 170, (40,70) => 55, (-3,4) => 0, (-10,11) => -10,
            _ => throw new InvalidOperationException($"Unexpected draw {min},{max}") };
        public int Next(int max) => max == 3 ? 0 : throw new InvalidOperationException();
        public int Next() => throw new InvalidOperationException();
        public double NextDouble() => throw new InvalidOperationException();
        public void NextBytes(byte[] buffer) => throw new InvalidOperationException();
    }

    private sealed class SeededRandom(int seed) : IWorldGenerationVanillaRandom
    {
        private readonly Random random = new(seed);
        public int Next() => random.Next(); public int Next(int max) => random.Next(max);
        public int Next(int min, int max) => random.Next(min, max);
        public double NextDouble() => random.NextDouble(); public void NextBytes(byte[] buffer) => random.NextBytes(buffer);
    }
}
