<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/TerraRuntime.World/TerraRuntime.World.csproj" />
    <ProjectReference Include="../../src/TerraRuntime.WorldGeneration/TerraRuntime.WorldGeneration.csproj" />
  </ItemGroup>
</Project>
