<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <RootNamespace>TerraRuntime</RootNamespace>
    <AssemblyName>TerraRuntime.Server</AssemblyName>
    <IsAotCompatible>true</IsAotCompatible>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <PublishAot>true</PublishAot>
    <IlcTreatWarningsAsErrors>true</IlcTreatWarningsAsErrors>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../TerraRuntime.Contracts/TerraRuntime.Contracts.csproj" />
    <ProjectReference Include="../TerraRuntime.Core/TerraRuntime.Core.csproj" />
    <ProjectReference Include="../TerraRuntime.Protocol.Multiplicity/TerraRuntime.Protocol.Multiplicity.csproj" />
  </ItemGroup>
</Project>
