<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Multiplicity" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/TerraRuntime.Protocol/TerraRuntime.Protocol.csproj" />
    <ProjectReference Include="../../src/TerraRuntime.Protocol.Multiplicity/TerraRuntime.Protocol.Multiplicity.csproj" />
  </ItemGroup>
</Project>
