<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <RootNamespace>TerraRuntime.Protocol.Multiplicity</RootNamespace>
    <AssemblyName>TerraRuntime.Protocol.Multiplicity</AssemblyName>
    <IsAotCompatible>true</IsAotCompatible>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Multiplicity" Version="2.7.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../TerraRuntime.Contracts/TerraRuntime.Contracts.csproj" />
    <ProjectReference Include="../TerraRuntime.Protocol/TerraRuntime.Protocol.csproj" />
    <ProjectReference Include="../TerraRuntime.World/TerraRuntime.World.csproj" />
  </ItemGroup>
</Project>
