<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <RootNamespace>TerraRuntime.Protocol.Multiplicity</RootNamespace>
    <AssemblyName>TerraRuntime.Protocol.Multiplicity</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Multiplicity" Version="2.6.3" />
  </ItemGroup>
</Project>
