<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <RootNamespace>TerraRuntime.World</RootNamespace>
    <AssemblyName>TerraRuntime.World</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TerraRuntime.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../TerraRuntime.Contracts/TerraRuntime.Contracts.csproj" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.0" />
  </ItemGroup>
</Project>
