namespace TerraRuntime.World;

/// <summary>
/// Terraria 1.4.5.8 frame-important tile mask for .wld format 326.
///
/// The packed mask is extracted by the Terraria World Generation Contract workflow from a world generated by the
/// official dedicated server binary whose SHA-256 is pinned by that workflow. Keeping the exact packed bytes here
/// lets fresh-world serialization share the same source-backed contract as vanilla SaveFileFormatHeader instead of
/// reconstructing this table from editor metadata or runtime reflection.
/// </summary>
public static class VanillaWorldFrameImportance326
{
    public const int Count = VanillaWorldFormat326.TileTypeCount;
    public const int PackedByteCount = (Count + 7) >> 3;
    public const int FrameImportantTileCount = 412;
    public const string PackedBitsSha256 = "414AFEB6156D7CB07A2DB0B3171A8703CC846EC998C9FB60BAA43F746B78DC69";

    private static readonly byte[] Packed =
    [
        0x38, 0xFC, 0x3F, 0xBD, 0x1E, 0x04, 0x86, 0x20, 0x80, 0xE7, 0xFE, 0xFF, 0xFF, 0x47, 0x06, 0x60,
        0xF3, 0xEF, 0x21, 0x00, 0x20, 0x78, 0x04, 0x0F, 0x00, 0x82, 0x96, 0x1F, 0x98, 0xFA, 0xFF, 0x40,
        0x00, 0xE0, 0xF8, 0xEF, 0xFF, 0xFF, 0x7F, 0xF4, 0x19, 0xC0, 0x0E, 0x20, 0xDC, 0x1F, 0xF0, 0x17,
        0xFC, 0x0F, 0x60, 0x7C, 0x98, 0x3B, 0xF8, 0x3F, 0xF0, 0xE3, 0xFF, 0x18, 0xF1, 0x6F, 0x0A, 0xE6,
        0xC0, 0xFF, 0x3E, 0xC4, 0xFB, 0xDF, 0xB1, 0x3F, 0xF8, 0xFF, 0xFF, 0xFF, 0xFF, 0xFB, 0xE1, 0xA5,
        0xFD, 0x7F, 0x97, 0x03, 0x00, 0x00, 0xE0, 0xFD, 0xEF, 0x1F, 0x7B, 0x20, 0x00, 0x80, 0x03
    ];

    public static ReadOnlySpan<byte> PackedBits => Packed;

    public static bool IsFrameImportant(int tileType)
    {
        ArgumentOutOfRangeException.ThrowIfNegative(tileType);
        ArgumentOutOfRangeException.ThrowIfGreaterThanOrEqual(tileType, Count);
        return (Packed[tileType >> 3] & (1 << (tileType & 7))) != 0;
    }

    public static byte[] CopyPackedBits() => (byte[])Packed.Clone();
}
