namespace TerraRuntime.World;

/// <summary>
/// Creates the identity/dimension prefix used by a fresh Terraria 1.4.5.8 world. Identity values remain explicit so
/// deterministic world generation is not quietly coupled to process-global randomness or wall-clock state.
/// </summary>
public static class VanillaFreshWorldHeader326
{
    // Extracted from a world generated by the SHA-256-pinned official TerrariaServer 1.4.5.8 binary in the
    // Terraria World Generation Contract workflow. This intentionally differs from early 1.4.5 builds, which used
    // 0x014500000001.
    public const ulong WorldGeneratorVersion = 0x014600000001UL;
    public const int TileSizePixels = 16;

    public static WorldFileHeader Create(
        string name,
        string seedText,
        int widthTiles,
        int heightTiles,
        Guid uniqueId,
        int worldId)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(name);
        ArgumentNullException.ThrowIfNull(seedText);
        ArgumentOutOfRangeException.ThrowIfLessThan(widthTiles, 1);
        ArgumentOutOfRangeException.ThrowIfLessThan(heightTiles, 1);
        if (uniqueId == Guid.Empty)
            throw new ArgumentException("Fresh worlds require a non-empty unique ID.", nameof(uniqueId));

        int rightWorld = checked(widthTiles * TileSizePixels);
        int bottomWorld = checked(heightTiles * TileSizePixels);

        return new WorldFileHeader(
            name,
            seedText,
            WorldGeneratorVersion,
            uniqueId,
            worldId,
            LeftWorld: 0,
            RightWorld: rightWorld,
            TopWorld: 0,
            BottomWorld: bottomWorld,
            new WorldDimensions(widthTiles, heightTiles));
    }
}
