using TerraRuntime.Network;

namespace TerraRuntime.Application.Operations;

internal readonly record struct RuntimeNetworkSnapshot(
    int ActiveConnections,
    int RegisteredConnections,
    long AcceptedConnections,
    long RejectedConnections,
    int TrackedOutboundQueues,
    long QueuedOutboundFrames,
    long QueuedOutboundBytes,
    long PeakQueuedOutboundFrames,
    long PeakQueuedOutboundBytes,
    long RejectedOutboundFrames,
    int SlowClients,
    ReadOnlyMemory<RuntimeConnectionQueueDetail> TopOutboundQueues,
    int TrackedInboundRates,
    long InboundWindowFrames,
    long InboundWindowBytes,
    long InboundTotalFrames,
    long InboundTotalBytes,
    long RejectedInboundFrames,
    ReadOnlyMemory<RuntimeConnectionRateDetail> TopInboundRates,
    long RelayedAppearanceFrames,
    long AppearanceBaselineFrames,
    long RelayedEquipmentFrames,
    long EquipmentBaselineFrames,
    long DroppedEquipmentSnapshotUpdates,
    long PlayerActiveBaselineFrames,
    long PlayerDeactivationFrames,
    long RelayedMovementFrames,
    long MovementResyncFrames,
    DateTimeOffset CapturedAtUtc,
    long NpcRelayedFrames = 0,
    long NpcBaselineFrames = 0,
    long NpcRejectedFrames = 0,
    long NpcUnsupportedCommits = 0,
    long ProjectileRelayedFrames = 0,
    long ProjectileBaselineFrames = 0,
    long ProjectileRejectedFrames = 0,
    long ProjectileUnsupportedCommits = 0,
    long WorldItemRelayedFrames = 0,
    long WorldItemRejectedFrames = 0,
    long WorldItemUnsupportedCommits = 0,
    long AdmissionCapacityRejectedConnections = 0,
    long AdmissionRateRejectedConnections = 0,
    long StopProtocolFailures = 0,
    long StopRateLimited = 0,
    long StopInvalidHandshake = 0,
    long StopUnsupportedProtocol = 0,
    long StopSlowClient = 0,
    long StopApplicationStopped = 0,
    long StopHandshakeTimeout = 0,
    long StopIdleTimeout = 0,
    long StopJoinTimeout = 0,
    long RejectedMalformedProtocol = 0,
    long RejectedRateLimited = 0,
    long RejectedInvalidState = 0,
    long RejectedGameplay = 0,
    long RejectedBackpressure = 0,
    long StopFrameRejected = 0,
    long MessageInboundFrames = 0,
    long MessageInboundBytes = 0,
    long MessageOutboundFrames = 0,
    long MessageOutboundBytes = 0,
    long UnknownInboundMessages = 0,
    long UnknownOutboundMessages = 0,
    long MalformedInboundMessages = 0,
    long MalformedOutboundMessages = 0,
    TimeSpan MessageTrafficWindow = default,
    ReadOnlyMemory<TerrariaMessageTrafficDetail> MessageTraffic = default,
    ReadOnlyMemory<TerrariaMessageTrafficDetail> TopMessageTraffic = default,
    int OutboundStructuralMaxFrames = 0,
    long OutboundStructuralMaxQueuedBytes = 0,
    int OutboundFrameUtilizationBasisPoints = 0,
    int OutboundByteUtilizationBasisPoints = 0,
    int OutboundMeasuredFramesWithHeadroom = 0,
    long OutboundMeasuredBytesWithHeadroom = 0,
    int OutboundRecommendedMaxFrames = 0,
    long OutboundRecommendedMaxQueuedBytes = 0,
    bool OutboundSizingHasMeasurements = false,
    bool OutboundSizingRequiresReview = false);
