using TerraRuntime.World;

namespace TerraRuntime.Application.Operations;

internal readonly record struct RuntimeWorldPersistenceSnapshot(
    bool AcceptingRequests,
    bool TileShadowReady,
    int RemainingBootstrapSections,
    int PendingDirtyTileSections,
    bool SaveRequested,
    bool WriteActive,
    bool PendingWrite,
    long AcceptedSnapshots,
    long StartedWrites,
    long CompletedWrites,
    long CoalescedSnapshots,
    long FailedWrites,
    double LastSnapshotCaptureMilliseconds = 0d,
    double LastSerializationMilliseconds = 0d,
    double LastWriteMilliseconds = 0d,
    double TotalSnapshotCaptureMilliseconds = 0d,
    double TotalSerializationMilliseconds = 0d,
    double TotalWriteMilliseconds = 0d);

internal readonly record struct RuntimeWorldSnapshot(
    bool Ready,
    string Name,
    int WorldId,
    Guid UniqueId,
    int FormatVersion,
    ulong WorldGeneratorVersion,
    int WidthTiles,
    int HeightTiles,
    int TileCount,
    int ChestCount,
    int SignCount,
    int TownNpcCount,
    int PersistentNpcCount,
    int TileEntityCount,
    int PressurePlateCount,
    int TownRoomCount,
    bool RuntimeCacheHit,
    string InitialCacheResult,
    int CacheParallelReads,
    double FileReadMilliseconds,
    double CacheLoadMilliseconds,
    double CanonicalWorldLoadMilliseconds,
    double CacheWriteMilliseconds,
    double BootstrapMilliseconds,
    double WorldReadyMilliseconds,
    double NetworkReadyMilliseconds,
    DateTimeOffset CapturedAtUtc,
    bool RuntimeClockAvailable = false,
    double RuntimeTime = 0d,
    bool RuntimeDayTime = false,
    VanillaMoonPhase RuntimeMoonPhase = VanillaMoonPhase.Full,
    double RuntimeSlimeRainTime = 0d,
    int RuntimeDayRate = 0,
    bool SectionCacheAvailable = false,
    int SectionCacheDirtyBacklog = 0,
    int SectionCacheInFlight = 0,
    int SectionCacheEntries = 0,
    int SectionCacheMaximumEntries = 0,
    long SectionCacheBytes = 0,
    long SectionCacheSubmitted = 0,
    long SectionCacheRejected = 0,
    long SectionCachePublished = 0,
    long SectionCacheStaleResults = 0,
    long SectionCacheEncodeFailures = 0,
    long SectionCachePublishRejections = 0,
    int SectionCacheActiveWorkers = 0,
    int SectionCachePendingWork = 0,
    double SectionCacheTotalEncodeMilliseconds = 0d,
    long SectionCacheHits = 0,
    long SectionCacheMisses = 0,
    long SectionCacheStaleReads = 0,
    long SectionCacheWaits = 0,
    long SectionCacheWaitCompletions = 0,
    long SectionCacheWaitTimeouts = 0,
    long SectionCacheOnDemandRequests = 0,
    long SectionCacheOnDemandUniqueRequests = 0,
    long SectionCacheOnDemandDeduplicatedRequests = 0,
    int SectionCacheOnDemandPendingRequests = 0,
    long SectionCacheOnDemandRejectedRequests = 0,
    int SectionCacheOnDemandCapacity = 0,
    long SectionCacheDirtyDeferredForOnDemand = 0,
    RuntimeWorldPersistenceSnapshot? Persistence = null,
    int InitialCacheDetailCode = 0);
