// <auto-generated>
// Generated by tools/ci/generate_item_prefix_world_table.py; do not edit by hand.
// Official 1.4.5.8 ItemVariants selection and Item.Prefix acceptance; numeric metadata only.
// Independent 200-cell fixture canonical UTF-8/LF SHA256: 06b43233c3e384da111f5486036069ab238d3763658df890a5dd0d02a5b4e6d9
// Normal prefix table canonical UTF-8/LF SHA256: 8c69f3927d4495eeed9ad3762a5630c01ea2356fad63b8a65bc91d4c3886ca68
// Original capture manifest SHA256: 21d858114ce53563937843010dd4df64af3e06a9bb49b68cf79588df4fa6bde6
// </auto-generated>
using TerraRuntime.Contracts.Gameplay;

namespace TerraRuntime.Gameplay.Items;

/// <summary>Known source world flags; null at the call boundary means unknown provenance.</summary>
public readonly record struct VanillaItemPrefixWorld1458(bool RemixWorld, bool GetGoodWorld, bool SkyblockWorld);

internal static class PrefixWorldRecords1458
{
    internal static bool HasVariant(int item) => item is 112 or 157 or 197 or 517 or 544 or 556 or 557 or 683 or 725 or 1314 or 1319 or 1325 or 2623 or 3069 or 4060 or 5147 or 5279 or 5280 or 5281 or 5282 or 5283 or 5284 or 5334 or 5687 or 5688;

    internal static bool IsVariantActive(int item, in VanillaItemPrefixWorld1458 world) => item switch
    {
        112 => world.RemixWorld,
        157 => world.RemixWorld,
        197 => world.GetGoodWorld,
        517 => world.RemixWorld,
        544 => world.RemixWorld && world.GetGoodWorld,
        556 => world.RemixWorld && world.GetGoodWorld,
        557 => world.RemixWorld && world.GetGoodWorld,
        683 => world.RemixWorld,
        725 => world.RemixWorld,
        1314 => world.RemixWorld,
        1319 => world.RemixWorld,
        1325 => world.RemixWorld,
        2623 => world.RemixWorld,
        3069 => world.RemixWorld,
        4060 => world.GetGoodWorld,
        5147 => world.RemixWorld,
        5279 => world.RemixWorld,
        5280 => world.RemixWorld,
        5281 => world.RemixWorld,
        5282 => world.RemixWorld,
        5283 => world.RemixWorld,
        5284 => world.RemixWorld,
        5334 => world.RemixWorld && world.GetGoodWorld,
        5687 => world.SkyblockWorld,
        5688 => world.SkyblockWorld,
        _ => false
    };

    internal static bool TryGet(ItemTypeId item, in VanillaItemPrefixWorld1458 world, out VanillaItemPrefixRecord1458 record)
    {
        // Seven source variant identities cannot receive prefixes in any of the eight contexts.
        if (!VanillaItemPrefixTable1458.TryGet(item, out record)) return false;
        if (!IsVariantActive(item.Value, in world)) return true;
        record = item.Value switch
        {
            112 => record with { Damage = 85, UseAnimation = 12, Mana = 9 },
            157 => record with { Damage = 90, UseAnimation = 10, Mana = 7 },
            197 => record with { Damage = 49, UseAnimation = 12, Mana = 0 },
            517 => record with { Damage = 14, UseAnimation = 15, Mana = 5 },
            683 => record with { Damage = 77, UseAnimation = 27, Mana = 9 },
            725 => record with { Damage = 8, UseAnimation = 17, Mana = 0 },
            1314 => record with { Damage = 18, UseAnimation = 25, Mana = 0 },
            1319 => record with { Damage = 22, UseAnimation = 6, Mana = 0 },
            1325 => record with { Damage = 60, UseAnimation = 15, Mana = 0 },
            2623 => record with { Damage = 5, UseAnimation = 9, Mana = 5 },
            3069 => record with { Damage = 40, UseAnimation = 10, Mana = 6 },
            4060 => record with { Damage = 54, UseAnimation = 18, Mana = 0 },
            5147 => record with { Damage = 42, UseAnimation = 10, Mana = 6 },
            5282 => record with { Damage = 6, UseAnimation = 29, Mana = 0 },
            5283 => record with { Damage = 4, UseAnimation = 30, Mana = 0 },
            5284 => record with { Damage = 8, UseAnimation = 23, Mana = 0 },
            5687 => record with { Damage = 9, UseAnimation = 24, Mana = 0 },
            5688 => record with { Damage = 12, UseAnimation = 30, Mana = 0 },
            _ => record
        };
        return true;
    }
}
