// <auto-generated>
// Independent official 1.4.5.8 AI_087 material cannon SetDefaults and Prefix(-1) facts.
// </auto-generated>
using TerraRuntime.Contracts.Gameplay;
namespace TerraRuntime.Gameplay.Items;
public static class VanillaBigMimicCannonItemCatalog1458
{
    public static bool TryGet(ItemTypeId type, out VanillaItemDefinition definition)
    {
        (int Width, int Height)? size = type.Value switch
        {
            2 => (12, 12),
            3 => (12, 12),
            61 => (12, 12),
            836 => (12, 12),
            409 => (12, 12),
            593 => (12, 12),
            664 => (12, 12),
            169 => (12, 12),
            370 => (12, 12),
            1246 => (12, 12),
            408 => (12, 12),
            3271 => (12, 12),
            3277 => (12, 12),
            3339 => (12, 12),
            3276 => (12, 12),
            3272 => (12, 12),
            3274 => (12, 12),
            3275 => (12, 12),
            3338 => (12, 12),
            176 => (12, 12),
            172 => (12, 12),
            424 => (12, 12),
            1103 => (12, 12),
            3087 => (12, 12),
            3066 => (12, 12),
            9 => (8, 10),
            2503 => (8, 10),
            2504 => (8, 10),
            619 => (8, 10),
            911 => (8, 10),
            621 => (8, 10),
            620 => (8, 10),
            1727 => (8, 10),
            276 => (12, 12),
            4564 => (14, 14),
            751 => (12, 12),
            1124 => (12, 12),
            1125 => (12, 12),
            824 => (12, 12),
            129 => (12, 12),
            131 => (12, 12),
            607 => (12, 12),
            594 => (12, 12),
            883 => (12, 12),
            414 => (12, 12),
            413 => (12, 12),
            609 => (12, 12),
            4050 => (14, 14),
            192 => (12, 12),
            412 => (12, 12),
            _ => null
        };
        definition = default;
        if (size is not {} body) return false;
        definition = new(type, new(body.Width, body.Height, 9999), null, null, null,
            new(body.Width, body.Height, false, VanillaItemPrefixFamily.None));
        return true;
    }
}
