namespace TerraRuntime.Contracts.Runtime;

public readonly record struct GameLoopSnapshot(
    long Tick,
    int GameThreadId,
    int CommandsProcessed,
    int PendingCommands,
    int DeferredCommands,
    long RejectedCommands,
    long CommandBudgetExhaustions,
    bool LastCommandBudgetExhausted,
    double OldestPendingCommandAgeMilliseconds,
    long MissedTickDeadlines,
    bool CpuTimeAvailable,
    double LastTickMilliseconds,
    double WorstTickMilliseconds,
    double LastTickCpuMilliseconds,
    double WorstTickCpuMilliseconds,
    double LastIngressMilliseconds,
    double WorstIngressMilliseconds,
    double LastCommandMilliseconds,
    double WorstCommandMilliseconds,
    double LastUpdateMilliseconds,
    double WorstUpdateMilliseconds,
    GameLoopPhase SlowestLastPhase,
    double SlowestLastPhaseMilliseconds,
    DateTimeOffset CapturedAtUtc);
