"""Regenerate the source-derived item placement table.

The table is not hand-written. It is lifted from the pinned official TerrariaServer 1.4.5.8 assembly by
running `Item.SetDefaults` for every item id and recording the placement fields the runtime consumes.

To reproduce:

    dotnet build .cache/itemdefs-probe/Probe.csproj -c Release
    .cache/itemdefs-probe/bin/Release/net48/ItemDefsProbe.exe > itemdefs.tsv
    python tools/ci/generate_item_placement_table.py itemdefs.tsv

The probe lives under .cache (untracked) because it references the pinned assembly, which the repository does
not carry. Regenerating and diffing the emitted file is how this table is audited.
"""

import io
import sys

OUTPUT = "src/TerraRuntime.Gameplay/Items/VanillaItemPlacementTable1458.cs"

HEADER = """// <auto-generated>
// Derived from the pinned official TerrariaServer 1.4.5.8 assembly by
// tools/ci/generate_item_placement_table.py. Do not edit by hand: regenerate from the probe and diff.
// </auto-generated>
using TerraRuntime.Contracts.Gameplay;

namespace TerraRuntime.Gameplay.Items;

/// <summary>
/// Every TerrariaServer 1.4.5.8 item that places a tile or a wall, with the fields placement needs:
/// <c>Item.createTile</c>, <c>Item.createWall</c>, <c>Item.placeStyle</c> and <c>Item.consumable</c>.
/// </summary>
/// <remarks>
/// <para>
/// This table exists because the hand-written definition catalog could only ever cover a handful of items, and
/// a server that refuses every placement it has not been told about individually cannot be built in. The values
/// come from running <c>Item.SetDefaults</c> over every id inside the pinned assembly, so they are the source's
/// own defaults rather than a transcription.
/// </para>
/// <para>
/// Layout: records sorted by item id, four little-endian <c>int16</c> each - id, createTile, createWall, and
/// placeStyle with the consumable flag in bit 15. A value of <c>-1</c> means the item does not place that kind.
/// No item in 1.4.5.8 places both a tile and a wall, and placeStyle never exceeds 315, which is what leaves
/// bit 15 free. Lookup is a binary search over the id field.
/// </para>
/// </remarks>
public static class VanillaItemPlacementTable1458
{
    /// <summary>Number of items in the table.</summary>
    public const int Count = @@COUNT@@;

    /// <summary>Items that place a tile.</summary>
    public const int TilePlacingCount = @@TILE@@;

    /// <summary>Items that place a wall.</summary>
    public const int WallPlacingCount = @@WALL@@;

    private const int RecordBytes = 8;

    private static ReadOnlySpan<byte> Records =>
    [
@@RECORDS@@
    ];

    /// <summary>
    /// Looks up an item's placement fields. Returns false for an item that places nothing, which is the
    /// overwhelming majority of the item table.
    /// </summary>
    public static bool TryGet(ItemTypeId type, out VanillaItemPlacementRecord1458 record)
    {
        record = default;
        int id = type.Value;
        if ((uint)id > ushort.MaxValue)
            return false;

        ReadOnlySpan<byte> records = Records;
        int low = 0;
        int high = (records.Length / RecordBytes) - 1;
        while (low <= high)
        {
            int middle = (low + high) >> 1;
            int offset = middle * RecordBytes;
            int candidate = records[offset] | (records[offset + 1] << 8);
            if (candidate == id)
            {
                short createTile = (short)(records[offset + 2] | (records[offset + 3] << 8));
                short createWall = (short)(records[offset + 4] | (records[offset + 5] << 8));
                int packedStyle = records[offset + 6] | (records[offset + 7] << 8);
                record = new VanillaItemPlacementRecord1458(
                    createTile,
                    createWall,
                    (short)(packedStyle & 0x7FFF),
                    (packedStyle & 0x8000) != 0);
                return true;
            }

            if (candidate < id)
                low = middle + 1;
            else
                high = middle - 1;
        }

        return false;
    }
}

/// <summary>
/// One item's placement fields as the source defines them. <c>-1</c> in either identity means the item does not
/// place that kind.
/// </summary>
public readonly record struct VanillaItemPlacementRecord1458(
    short CreateTile,
    short CreateWall,
    short PlaceStyle,
    bool Consumable)
{
    public bool PlacesTile => CreateTile >= 0;

    public bool PlacesWall => CreateWall >= 0;
}
"""


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2

    rows = []
    with io.open(sys.argv[1], encoding="utf-8") as handle:
        for index, line in enumerate(handle):
            if index == 0:
                continue
            fields = line.rstrip("\n").split("\t")
            if len(fields) < 5:
                continue
            item_id = int(fields[0])
            create_tile = int(fields[1])
            create_wall = int(fields[2])
            place_style = int(fields[3])
            consumable = int(fields[4]) != 0
            if create_tile < 0 and create_wall < 0:
                continue
            if not 0 <= item_id <= 0xFFFF:
                raise ValueError("item id %d does not fit the record layout" % item_id)
            if not -1 <= create_tile <= 0x7FFF or not -1 <= create_wall <= 0x7FFF:
                raise ValueError("item %d identities do not fit int16" % item_id)
            if not 0 <= place_style <= 0x7FFF:
                raise ValueError("item %d placeStyle %d does not fit 15 bits" % (item_id, place_style))
            rows.append((item_id, create_tile, create_wall, place_style, consumable))

    rows.sort(key=lambda row: row[0])

    payload = []
    for item_id, create_tile, create_wall, place_style, consumable in rows:
        packed_style = place_style | (0x8000 if consumable else 0)
        for value in (item_id, create_tile & 0xFFFF, create_wall & 0xFFFF, packed_style):
            payload.append(value & 0xFF)
            payload.append((value >> 8) & 0xFF)

    lines = []
    for start in range(0, len(payload), 16):
        chunk = payload[start:start + 16]
        lines.append("        " + ", ".join("0x%02X" % byte for byte in chunk) + ",")
    if lines:
        lines[-1] = lines[-1].rstrip(",")

    text = (HEADER
            .replace("@@COUNT@@", str(len(rows)))
            .replace("@@TILE@@", str(sum(1 for row in rows if row[1] >= 0)))
            .replace("@@WALL@@", str(sum(1 for row in rows if row[2] >= 0)))
            .replace("@@RECORDS@@", "\n".join(lines)))

    with io.open(OUTPUT, "w", encoding="utf-8", newline="") as handle:
        handle.write(text)

    print("%s: %d records, %d bytes" % (OUTPUT, len(rows), len(payload)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
