"""Regenerate the source-derived natural-prefix table.

`Item.Prefix(-1)` draws from the shared generation stream, so every chest item that receives a natural prefix
moves that stream for everything placed after it. Reproducing it needs two things the runtime cannot guess: the
prefix family each item rolls from, and the four stat multipliers that decide whether a rolled prefix is kept or
rerolled. Both are lifted from the pinned official TerrariaServer 1.4.5.8 assembly rather than transcribed.

To reproduce:

    dotnet build .cache/prefix-probe/Probe.csproj -c Release
    .cache/prefix-probe/bin/Release/net48/PrefixProbe.exe table > prefix.tsv
    python tools/ci/generate_item_prefix_table.py prefix.tsv

The probe lives under .cache (untracked) because it references the pinned assembly, which the repository does
not carry. Regenerating and diffing the emitted file is how this table is audited.
"""

import io
import sys

OUTPUT = "src/TerraRuntime.Gameplay/Items/VanillaItemPrefixTable1458.cs"

HEADER = """// <auto-generated>
// Derived from the pinned official TerrariaServer 1.4.5.8 assembly by
// tools/ci/generate_item_prefix_table.py. Do not edit by hand: regenerate from the probe and diff.
// </auto-generated>
using TerraRuntime.Contracts.Gameplay;

namespace TerraRuntime.Gameplay.Items;

/// <summary>
/// Everything <c>Item.Prefix(-1)</c> reads while the world is being generated: which prefix family an item
/// rolls from, the four defaults that decide whether a rolled prefix survives, and the prefix multipliers
/// themselves.
/// </summary>
/// <remarks>
/// <para>
/// The roll matters far beyond the prefix byte it writes. It runs on the shared generation stream, and it
/// rerolls until it finds a prefix the item accepts, so an item whose stats reject half the family consumes a
/// different number of values than one that accepts everything. Getting the acceptance rule wrong desynchronises
/// every placement after the chest, not just the chest.
/// </para>
/// <para>
/// Only four of an item's defaults reach that rule: <c>damage</c>, <c>useAnimation</c>, <c>mana</c>, and whether
/// <c>knockBack</c> is exactly zero. <c>Item.TryGetPrefixStatMultipliersForItem</c> rejects a prefix whose damage,
/// speed or mana multiplier rounds the stat back to itself, and any knockback modifier on an item with no
/// knockback. Nothing else about the item is read, which is what keeps this table small.
/// </para>
/// <para>
/// Item layout: @@ITEMCOUNT@@ records sorted by item id, eight bytes each - id as little-endian
/// <c>uint16</c>, damage as little-endian <c>int16</c>, useAnimation, mana, and a flags byte holding the family
/// index in bits 0-2 and the zero-knockback flag in bit 3. Lookup is a binary search over the id field. Items
/// that cannot have prefixes at all are absent, which is most of the item table.
/// </para>
/// </remarks>
public static class VanillaItemPrefixTable1458
{
    /// <summary>Number of items in 1.4.5.8 that can receive a prefix.</summary>
    public const int Count = @@ITEMCOUNT@@;

    /// <summary>One past the highest prefix id the multiplier table covers.</summary>
    public const int PrefixCount = @@PREFIXCOUNT@@;

    private const int RecordBytes = 8;

    private static ReadOnlySpan<byte> Records =>
    [
@@RECORDS@@
    ];

    // The eight PrefixLegacy.Prefixes arrays, concatenated in the order GetRollablePrefixes tests them:
    // swords, spears, guns and bows, magic, summons, boomerangs and chakrams, the Terrarian yoyo, accessories.
    private static ReadOnlySpan<byte> FamilyPrefixes =>
    [
@@FAMILIES@@
    ];

    private static ReadOnlySpan<byte> FamilyStarts => [@@FAMILYSTARTS@@];

    // Three multipliers per prefix - damage, speed, mana cost - indexed by prefix id times three. Prefix zero
    // leads with three ones, which is what makes the no-prefix result accept unconditionally.
    private static ReadOnlySpan<float> Multipliers =>
    [
@@MULTIPLIERS@@
    ];

    // Bit 0: the prefix changes knockback, so an item with no knockback rejects it.
    // Bit 1: PrefixID.Sets.ReducedNaturalChance, which costs the roll an extra value.
    private static ReadOnlySpan<byte> PrefixFlags =>
    [
@@PREFIXFLAGS@@
    ];

    /// <summary>
    /// Looks up the defaults the prefix roll reads. Returns false for an item that cannot have prefixes, which
    /// is how <c>Item.CanHavePrefixes</c> refuses before drawing anything.
    /// </summary>
    public static bool TryGet(ItemTypeId type, out VanillaItemPrefixRecord1458 record)
    {
        record = default;
        int id = type.Value;
        if ((uint)id > ushort.MaxValue)
            return false;

        ReadOnlySpan<byte> records = Records;
        int low = 0;
        int high = (records.Length / RecordBytes) - 1;
        while (low <= high)
        {
            int middle = (low + high) >> 1;
            int offset = middle * RecordBytes;
            int candidate = records[offset] | (records[offset + 1] << 8);
            if (candidate == id)
            {
                byte flags = records[offset + 6];
                record = new VanillaItemPrefixRecord1458(
                    (short)(records[offset + 2] | (records[offset + 3] << 8)),
                    records[offset + 4],
                    records[offset + 5],
                    flags & 0x07,
                    (flags & 0x08) != 0);
                return true;
            }

            if (candidate < id)
                low = middle + 1;
            else
                high = middle - 1;
        }

        return false;
    }

    /// <summary>The prefixes a family rolls from, in the source's own order.</summary>
    public static ReadOnlySpan<byte> GetFamily(int family)
    {
        ReadOnlySpan<byte> starts = FamilyStarts;
        int start = starts[family];
        int end = family + 1 < starts.Length ? starts[family + 1] : FamilyPrefixes.Length;
        return FamilyPrefixes[start..end];
    }

    /// <summary>
    /// Source <c>Item.TryGetPrefixStatMultipliersForItem</c>, reduced to the question the roll asks of it:
    /// does this item keep this prefix, or reroll?
    /// </summary>
    public static bool Accepts(in VanillaItemPrefixRecord1458 record, int prefix)
    {
        ReadOnlySpan<float> multipliers = Multipliers;
        float damageMultiplier = multipliers[prefix * 3];
        float speedMultiplier = multipliers[prefix * 3 + 1];
        float manaMultiplier = multipliers[prefix * 3 + 2];

        // The products are taken in double. The source writes them in float, but the pinned x86 server
        // evaluates them wider than float before rounding, and three items turn on the difference: at
        // useAnimation ten, a float-rounded 9.5 rounds back up to ten and rejects the prefix, while the exact
        // 9.49999988 the server computes rounds down to nine and keeps it. Double reproduces the server
        // because the product of a stat this small and a single-precision multiplier is exact in double.
        if (damageMultiplier != 1f && Math.Round(record.Damage * (double)damageMultiplier) == record.Damage)
            return false;
        if (speedMultiplier != 1f &&
            Math.Round(record.UseAnimation * (double)speedMultiplier) == record.UseAnimation)
            return false;
        if (manaMultiplier != 1f && Math.Round(record.Mana * (double)manaMultiplier) == record.Mana)
            return false;
        return (PrefixFlags[prefix] & 0x01) == 0 || !record.HasNoKnockBack;
    }

    /// <summary>Source <c>PrefixID.Sets.ReducedNaturalChance</c>.</summary>
    public static bool HasReducedNaturalChance(int prefix) => (PrefixFlags[prefix] & 0x02) != 0;
}

/// <summary>
/// The four <c>Item.SetDefaults</c> fields a natural prefix roll reads, plus the family it rolls from.
/// </summary>
public readonly record struct VanillaItemPrefixRecord1458(
    short Damage,
    byte UseAnimation,
    byte Mana,
    int Family,
    bool HasNoKnockBack);
"""


def byte_lines(payload):
    lines = []
    for start in range(0, len(payload), 16):
        chunk = payload[start:start + 16]
        lines.append("        " + ", ".join("0x%02X" % byte for byte in chunk) + ",")
    if lines:
        lines[-1] = lines[-1].rstrip(",")
    return "\n".join(lines)


def format_float(value):
    text = repr(float(value))
    if text.endswith(".0"):
        text = text[:-2]
    return text + "f"


def float_lines(values):
    lines = []
    for start in range(0, len(values), 9):
        chunk = values[start:start + 9]
        lines.append("        " + ", ".join(format_float(value) for value in chunk) + ",")
    if lines:
        lines[-1] = lines[-1].rstrip(",")
    return "\n".join(lines)


def main():
    if len(sys.argv) != 2:
        print(__doc__)
        return 2

    items = []
    families = {}
    prefixes = {}
    section = "items"
    with io.open(sys.argv[1], encoding="utf-8") as handle:
        for index, line in enumerate(handle):
            line = line.rstrip("\n")
            if index == 0:
                continue
            if line == "#families":
                section = "families"
                continue
            if line == "#prefixes":
                section = "prefixes"
                continue
            fields = line.split("\t")
            if section == "items":
                item_id, family, damage, use_animation, mana, knock_back = fields
                items.append((int(item_id), int(family), int(damage), int(use_animation),
                              int(mana), float(knock_back) == 0.0))
            elif section == "families":
                families[int(fields[0])] = [int(value) for value in fields[1:]]
            else:
                prefixes[int(fields[0])] = (float(fields[1]), float(fields[2]), float(fields[3]),
                                            float(fields[4]) != 1.0, fields[5] == "1")

    items.sort(key=lambda row: row[0])

    payload = []
    for item_id, family, damage, use_animation, mana, no_knock_back in items:
        if not 0 <= item_id <= 0xFFFF:
            raise ValueError("item id %d does not fit the record layout" % item_id)
        if not -0x8000 <= damage <= 0x7FFF:
            raise ValueError("item %d damage %d does not fit int16" % (item_id, damage))
        if not 0 <= use_animation <= 0xFF or not 0 <= mana <= 0xFF:
            raise ValueError("item %d use time or mana does not fit a byte" % item_id)
        if not 0 <= family <= 7:
            raise ValueError("item %d family %d does not fit three bits" % (item_id, family))
        payload.append(item_id & 0xFF)
        payload.append((item_id >> 8) & 0xFF)
        payload.append(damage & 0xFF)
        payload.append((damage >> 8) & 0xFF)
        payload.append(use_animation)
        payload.append(mana)
        payload.append(family | (0x08 if no_knock_back else 0))
        payload.append(0)

    family_payload = []
    family_starts = []
    for family in range(len(families)):
        family_starts.append(len(family_payload))
        family_payload.extend(families[family])
    if any(value > 0xFF for value in family_payload):
        raise ValueError("a prefix id does not fit a byte")
    if family_starts[-1] > 0xFF:
        raise ValueError("the family table no longer fits byte offsets")

    prefix_count = max(prefixes) + 1
    multipliers = [1.0, 1.0, 1.0]
    prefix_flags = [0]
    for prefix in range(1, prefix_count):
        damage_multiplier, speed_multiplier, mana_multiplier, changes_knock_back, reduced = prefixes[prefix]
        multipliers.extend([damage_multiplier, speed_multiplier, mana_multiplier])
        prefix_flags.append((0x01 if changes_knock_back else 0) | (0x02 if reduced else 0))

    text = (HEADER
            .replace("@@ITEMCOUNT@@", str(len(items)))
            .replace("@@PREFIXCOUNT@@", str(prefix_count))
            .replace("@@RECORDS@@", byte_lines(payload))
            .replace("@@FAMILIES@@", byte_lines(family_payload))
            .replace("@@FAMILYSTARTS@@", ", ".join(str(value) for value in family_starts))
            .replace("@@MULTIPLIERS@@", float_lines(multipliers))
            .replace("@@PREFIXFLAGS@@", byte_lines(prefix_flags)))

    with io.open(OUTPUT, "w", encoding="utf-8", newline="") as handle:
        handle.write(text)

    print("%s: %d items, %d prefixes, %d bytes" % (OUTPUT, len(items), prefix_count - 1, len(payload)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
